Enable Video Streaming by default
PX4/PX4-SITL_gazebo-classic pull request #118
Opened 2017-08-24 13:48 UTC by lbegani

This is to enable video streaming over UDP by default.
Would like to highlight following things- 
1. As mentioned while disabling, should we lower the camera image size (640x360) ?
2. Currently, the video stream from gazebo can be played running a gstreamer pipeline. However QGC is not able to play the video due to gstreamer errors (https://github.com/mavlink/qgroundcontrol/issues/5447). This is due to the color format mismatch. Adding color conversion(RGB->NV12) in the UDP streaming gst pipeline in GstCameraPlugin should fix this. However when I do that, I get following errors while running gazebo -

> [Err] [ConnectionManager.cc:119] Failed to connect to master in 30 seconds.
> [Err] [gazebo_shared.cc:83] Unable to initialize transport.
> [Err] [gazebo_client.cc:62] Unable to setup Gazebo

3. Another way to fix https://github.com/mavlink/qgroundcontrol/issues/5447 is to add videoconvert element in the video receiving gstreamer pipeline of QGC. When I do that, I can see video streams from gazebo in QGC. @dogmaphobic Is it OK to make this change in QGC?

2017-08-24 13:51 UTC, lbegani commented
@LorenzMeier Please review

2017-08-24 15:27 UTC, ChristophTobler commented
@lbegani Why should be enable it by default? I guess most people don't need it and it needs a lot of CPU. If you need it, you can just enable it locally.

2017-08-25 11:38 UTC, lbegani commented
@ChristophTobler Not sure, but I guess if its not enabled by default, people will hardly use it even if they want to due to various reason.  It would be preferable to have it enabled in the code and provide a way for the user to enable/disable runtime (from the UI ?) Not sure if possible, any comment/concern/suggestion?

2017-08-25 19:28 UTC, LorenzMeier commented
I think the suggestion to enable / disable from the UI makes a lot of sense and could be built into the standard camera controls.

2017-08-26 14:14 UTC, dogmaphobic commented
>Adding color conversion(RGB->NV12)

Yes, all streams are expected to be YUV. RGB is rarely, if ever used for streaming.

2017-08-27 13:46 UTC, LorenzMeier commented
@lbegani I think we should convert it on the simulator side, e.g. using OpenCV (which is already used in the optical flow plugin).

2017-08-28 10:31 UTC, lbegani commented
@LorenzMeier  I haven't tried OpenCV but to do the color conversion in the simulator side, I tried to set caps (format = NV12) to the videoconvert element  in the UDP source pipeline (tested to work in terminal). It resulted in the following error while launching app. Could this be because simulator doesn't have enough cycles?

> [Err] [ConnectionManager.cc:119] Failed to connect to master in 30 seconds.
> [Err] [gazebo_shared.cc:83] Unable to initialize transport.
> [Err] [gazebo_client.cc:62] Unable to setup Gazebo

2017-08-31 10:11 UTC, lbegani commented
@LorenzMeier Added code for RGB to YUV, QGC is now able to display video.

2017-11-23 04:43 UTC, lbegani commented
@dogmaphobic @LorenzMeier @ChristophTobler Can you kindly review

2017-11-25 09:21 UTC, LorenzMeier commented
Could you rebase?

@tfoote is there any way for Gazebo to tell if a computer has good performance or not? We have features that we’d like to enable by default on beefy machines.

2017-11-25 22:49 UTC, tfoote commented
I don't know of a performance benchmark that can easily be tested for this. Are you looking for a runtime decision? In general I'd suggest that it default to off, and have a parameter that's easy to set to enable it. Having the behavior differ on different machines will be unexpected for developers and make testing debugging much harder.

2017-12-04 12:49 UTC, lbegani commented
@LorenzMeier @ChristophTobler @dogmaphobic 
I have added a button(GUI Overlay) to enable/disable streaming at runtime, kindly review. It would be nice if someone could test the changes on their setup.
![gazebo-streaming-off](https://user-images.githubusercontent.com/18675790/33553543-340baad4-d91f-11e7-854b-5cd19e50382e.png)
![gazebo-streaming-on](https://user-images.githubusercontent.com/18675790/33553560-434053c4-d91f-11e7-91fe-66986dd90261.png)

2017-12-30 16:02 UTC, LorenzMeier requested changes
@lbegani I just tried this on Mac OS and unfortunately you're getting bitten by Gazebo 8 using Qt5. We need to either support both Gazebo versions or work around the UI somehow.

2017-12-30 17:42 UTC, LorenzMeier commented
I've rebased and merged this. Thanks!

2017-12-30 17:42 UTC, closed without merging

2018-01-08 00:23 UTC, hamishwillee commented
@lbegani Any progress on supporting Gazebo8?

2018-01-08 04:14 UTC, lbegani commented
> Any progress on supporting Gazebo8?

I haven't looked into it yet. I will do that once I get some time, perhaps after a week or two