Actualize UUV Parameters and UUV Plugin
PX4/PX4-SITL_gazebo-classic pull request #130
Opened 2017-10-04 14:38 UTC by NRottmann

With this commit I actualize the parameter for the UUV HippoCampus from the Technical University Hamburg-Harburg. The parameters have now been determined by experiments.

2017-10-04 20:58 UTC, TSC21 commented on include/gazebo_uuv_plugin.h
> +    double absolute(double x);
you don't need this. You can simply use `std::abs( double arg )`.

2017-10-04 20:59 UTC, TSC21 commented on src/gazebo_uuv_plugin.cpp
> +// gives back absolute value of a double number
no need.

2017-10-04 20:59 UTC, TSC21 commented on src/gazebo_uuv_plugin.cpp
> +    math::Vector3 rotor_force(motor_force_constant_ * command_[i] * absolute(command_[i]), 0, 0);
`math::Vector3 rotor_force(motor_force_constant_ * command_[i] * std::abs(command_[i]), 0, 0);`

2017-10-04 20:59 UTC, TSC21 commented on src/gazebo_uuv_plugin.cpp
> +      propeller_direction * motor_torque_constant_ * command_[i] * absolute(command_[i]), 0, 0);
`propeller_direction * motor_torque_constant_ * command_[i] * std::abs(command_[i]), 0, 0);`

2017-10-04 21:02 UTC, TSC21 requested changes
Just remove the `absolute` method and replace with `std::abs()` and everything is good.

2017-10-05 08:26 UTC, NRottmann commented
Changes done

2017-10-06 15:51 UTC, TSC21 approved these changes

2017-10-06 15:51 UTC, merged

2017-10-06 15:51 UTC, TSC21 commented
Thanks!