Feature to add motor failure over ROS interface
PX4/PX4-SITL_gazebo-classic pull request #139
Opened 2017-11-11 08:57 UTC by siddhu45

This modification in the `gazebo_motor_failure_model` plugin will enable to simulate motor failure in the robot model in real time by subscribing to a rostopic `/gazebo/motor_failure/motor_number` [ex: [Publisher](https://drive.google.com/open?id=18uW0NMYJ-7YJcluNlkrneRmmSy7aRlPe) & [cfg](https://drive.google.com/open?id=190Mdq-2zdGiCqljhI_2AqJbDFN8huH-0)] and fail that motor by setting the `motor_constant_ = 0`. 

Any suggestions to make the code better are welcome. And if someone could contribute to making the rotor visually stop rotating when it fails, that would be great. 
Please review @TSC21

Thanks!
PS: Hope this one is correct. base fork: current master, from: my motor_failure branch.

2017-11-11 17:44 UTC, TSC21 commented on CMakeLists.txt
> -add_library(gazebo_irlock_plugin SHARED src/gazebo_irlock_plugin.cpp)
@siddhu45 You continue to not having the latest master from upstream. Please isse `git pull https://github.com/PX4/sitl_gazebo master` on you local repo, commit the changes and push again.

2017-11-11 17:45 UTC, TSC21 commented
@siddhu45 when you issue `caktin buil -DBUILD_ROS_INTERFACE=ON` does it build the plugin correctly? Also, you also have to add the ROS dependencies to `package.xml`.

2017-11-11 17:52 UTC, TSC21 requested changes
@siddhu45 I thank you for your commitment to this and for your intentions of helping. But in order for this to get in, there are some things that need to be addressed:
1. The plugin you are writing should not be a replacement of any plugin existing on this repo, neither a copy-paste with some mods. It should be a plugin that interacts with the existent ones. That means that this plugin will have the ROS subscriber and triggers a Gazebo msg received in the `gazebo_motor_plugin` that makes the motor stop. If it is not like that, it does not make sense to exist, since this is a feature and not a replacement.
2. You need to add the proper dependencies for this to be built, mainly on `package.xml`. You addressed the changes on `CMakeLists.txt` so the user can only build this if required, though they are not enough and seemed untested on your side.

2017-11-11 17:52 UTC, TSC21 commented on include/gazebo_motor_failure_model.h
> +/*
This is a copy-paste of the `gazebo_motor_model` plugin. This is not what is pretended. You have to create a plugin that does not replace `gazebo_motor_model` but either interacts with it.

2017-11-12 10:44 UTC, siddhu45 commented
@TSC21 Thanks for pointing out the errors and also for your time to make things clear for me and also explain. And frankly, yes, I didn't have the time to verify the changes. It is important for me if I am contributing then it has to be properly done so others can use it as well. I will first write the plugin properly, test it this week and then will do another proper PR. Sorry, for the constant errors on my part. See you with the proper changes soon. Thanks!

2017-11-12 15:22 UTC, TSC21 commented
No problem. Just let me know if you need some clarification. And thanks.

2017-11-14 10:19 UTC, closed without merging