plugins: vision: use complete visual odometry msg to send to the FCU
PX4/PX4-SITL_gazebo-classic pull request #201
Opened 2018-04-17 00:02 UTC by TSC21

Purpose: add a more complete simulated odometry data sent from Gazebo to the FCU.

2018-04-17 00:24 UTC, TSC21 commented
Well looks like CMake restarted checking for the ROS Mavlink version first again somehow without a visible reason (Seems the latest release is not available by apt-get yet). Have to check why.

2018-04-24 06:37 UTC, ChristophTobler requested changes
This doesn't seem to be tested... The gazebo error is resolved by the comment but still, if I run this PR with `EKF2_AID_MASK = 24` and `EKF2_HGT_MODE = 3` the vehicle immediately flies away after takeoff.

2018-04-24 06:37 UTC, ChristophTobler commented on src/gazebo_vision_plugin.cpp
> +    position->set_x(pose_model.Pos().Z() + noise_pos.Z() + _bias.Z());
`set_x()` -> `set_y()` and `set_z()`

2018-04-24 08:46 UTC, TSC21 commented on src/gazebo_vision_plugin.cpp
> +    position->set_x(pose_model.Pos().Z() + noise_pos.Z() + _bias.Z());
Yeah. Typo. Thanks.

2018-04-24 08:46 UTC, TSC21 commented
> This doesn't seem to be tested... The gazebo error is resolved by the comment but still, if I run this PR with `EKF2_AID_MASK = 24` and `EKF2_HGT_MODE = 3` the vehicle immediately flies away after takeoff.

Yes this still needs some extensive testing. Thanks for giving it a try @ChristophTobler. I will update you when I get this to a working stage.

2018-04-27 20:23 UTC, closed without merging