WIP add type and facing to lidar plugin
PX4/PX4-SITL_gazebo-classic pull request #306
Opened 2019-03-26 10:23 UTC by EliaTarasov

The intended goal of this PR is to remove `lidar_plugin` and `sonar_plugin` and to create unified `distance_sensor_plugin` instead. Currently `lidar_plugin` and `sonar_plugin` have almost the same distance models and their handling inside `mavlink_interface` is almost the same too.

2019-03-26 10:24 UTC, EliaTarasov commented
@TSC21 @julianoes what do you think? Is it worth to implement?
Thanks!

2019-03-26 10:27 UTC, TSC21 requested changes
I think that they can be kept in separate plugins as they have different different properties that can be explored. Or, those properties could be explored in the same plugin, though it can't be named lidar_plugin, as you seem to be keeping.

2019-03-26 10:45 UTC, EliaTarasov commented
> Or, those properties could be explored in the same plugin, though it can't be named lidar_plugin, as you seem to be keeping.

Yes `lidar_plugin` should be renamed of course. 

> I think that they can be kept in separate plugins as they have different different properties that can be explored.

Can you please specify these properties?
I think yes, the implementation of these plugins might have been different if an additional properties would have been specified. But for now these two plugins are almost identical.

2019-03-26 11:11 UTC, EliaTarasov commented
Would it be useful then to add only `facing` property to avoid it being [hardcoded](https://github.com/PX4/sitl_gazebo/blob/master/src/gazebo_mavlink_interface.cpp#L819)?

2019-03-28 11:13 UTC, EliaTarasov commented
Closed in favor of #308 .

2019-03-28 11:13 UTC, closed without merging