Video stream widget update for Gazebo 9+
PX4/PX4-SITL_gazebo-classic pull request #344
Opened 2019-09-06 08:38 UTC by RicardoM17

This PR makes possible the build of `gazebo_video_stream_widget` that was previously only being built for versions of Gazebo less than `8.0`.

It updates the `CMakeLists.txt` to include the required packages and links, as well as the header of `gazebo_video_stream_widget.h`.

Regarding this last part maybe it breaks this widget on the older versions of gazebo (can't really test right now). Possible solutions would be to find a way that it's builtable by all versions or depecrate it for older versions of Gazebo. I'm open to suggestions/help.

Thanks

2019-09-06 11:25 UTC, TSC21 requested changes
@RicardoM17 thanks for the fix. Though, you need to maintain the backwards compatibility in the header file.

2019-09-06 11:25 UTC, TSC21 commented on CMakeLists.txt
> +      find_package(Protobuf REQUIRED)
No need

2019-09-06 11:25 UTC, TSC21 commented on CMakeLists.txt
> +      find_package(gazebo REQUIRED)
No need as well

2019-09-06 11:25 UTC, TSC21 commented on CMakeLists.txt
> +    ${Qt5Core_LIBRARIES}
Requires indentation fix

2019-09-06 11:25 UTC, TSC21 commented on CMakeLists.txt
> +    message("Gazebo version: ${GAZEBO_VERSION}")
No need

2019-09-06 11:25 UTC, TSC21 commented on include/gazebo_video_stream_widget.h
> +#include <gazebo/transport/transport.hh>
Why is this removed? There must be a a purpose for this. If it is related with the Gazebo version, then you need to wrap this up in preprocessor directives that make the usage of one or another dependent of the Gazebo version.

2019-09-06 14:18 UTC, RicardoM17 commented
I believe that it's fixed now. Thanks for the feedback and suggestions.

Should be GTM.

2019-09-09 15:23 UTC, TSC21 approved these changes
LGTM. Thanks @RicardoM17

2019-09-09 15:24 UTC, merged