Set wind_pluggin to zero for Gazebo Plane model
PX4/PX4-SITL_gazebo-classic pull request #364
Opened 2019-10-31 13:30 UTC by Antiheavy

As documented here https://github.com/PX4/sitl_gazebo/issues/287 the Gazebo wind_pluggin doesn't work properly for the Gazebo Plane model.  This PR sets the wind_pluggin values to zero for the Plane model so that it will fly correctly in simulation.

In the long term, we should figure out exactly why the wind_pluggin does not work properly with gazebo plane model.  I suspect it might have something to do with improper or incomplete modeling of the airplane aerodynamics as it relates to the wind_pluggin, but I don't have the coding skills to really figure this out for sure. 

Questions:
1) if this PR is viewed as too much a hack, feel free to reject it, or suggest improvements.
2) maybe there are other vehicle models that are also affected?  Should we fix it for them too?

2019-11-01 02:33 UTC, dagar commented
Do we want to disable the plugin entirely?

2019-11-01 07:44 UTC, LorenzMeier approved these changes

2019-11-01 13:08 UTC, Antiheavy commented
> Do we want to disable the plugin entirely?

That is another option.  I suggested setting the values to zero in the plane models for this PR because it is the method I've used and tested in SITL; so I know it works.

2019-11-02 11:41 UTC, TSC21 requested changes
> > Do we want to disable the plugin entirely?
> 
> That is another option. I suggested setting the values to zero in the plane models for this PR because it is the method I've used and tested in SITL; so I know it works.

I think it's preferable to disable the wind plugin entirely by comment it and also add a comment above it explaining why it is deactivated.

2019-11-15 18:22 UTC, Jaeyoung-Lim commented
@Antiheavy The reason behind the wind plugin not working properly is because it does not generate lift or drag.

If you look at how the `wind_plugin` is written, the wind plugin applies additional torque / force on to the `base_link` rather than changing the airspeed. Therefore, if you have a head wind with the same ground speed you will not have more lift, but just drag.

2019-11-15 23:25 UTC, Antiheavy commented
Thanks @Jaeyoung-Lim !  I would like to follow @TSC21 suggestion to comment out the wind plugin with an appropriate comment explaining why.  I just haven't gotten around to learning how to do that properly in XML or whatever the file type is....  one of these days!

2019-11-18 11:46 UTC, TSC21 requested changes

2019-11-18 11:46 UTC, TSC21 commented on models/plane/plane.sdf
> +      <xyzOffset>0 0 0</xyzOffset>
@Antiheavy as simple as:
```suggestion
    <!-- Wind plugin deactivated as the wind plugin is not affecting the control surfaces lift and drag.
           This requires an update on the lift/drag plugin as well. -->
    <!-- <plugin name='wind_plugin' filename='libgazebo_wind_plugin.so'>
      <frameId>base_link</frameId>
      <linkName>base_link</linkName>
      <robotNamespace/>
      <xyzOffset>1 0 0</xyzOffset>
      <windDirection>0 1 0</windDirection>
      <windForceMean>0.7</windForceMean>
      <windGustDirection>0 0 0</windGustDirection>
      <windGustDuration>0</windGustDuration>
      <windGustStart>0</windGustStart>
      <windGustForceMean>0</windGustForceMean>
    </plugin> -->
```

2019-11-24 15:52 UTC, Antiheavy commented
@TSC21 I think I incorporated your suggestion and reverted my original changes.  Can you review quick?

2019-11-24 15:54 UTC, Antiheavy commented
@Jaeyoung-Lim does your new PR here: https://github.com/PX4/sitl_gazebo/pull/375 make this PR obsolete?

2019-11-26 17:47 UTC, Jaeyoung-Lim commented
@Antiheavy Depends on what we want. If you want to disable the wind plugin it is not obsolete. If you wanted to disable the wind plugin because it was unrealistic, then it can be replaced.

2019-11-26 18:41 UTC, Antiheavy commented
> If you wanted to disable the wind plugin because it was unrealistic, then it can be replaced.

@Jaeyoung-Lim I think your PR fixes the problem so I'll close this. thanks!

2019-11-26 18:41 UTC, closed without merging