Set image storage directory from environment variable
PX4/PX4-SITL_gazebo-classic pull request #371
Opened 2019-11-15 22:23 UTC by Jaeyoung-Lim

This PR enables setting the path of the directory where the images taken by the `geotagged_camera_plugin` be saved in a path specified by a environment variable `PX4_STORAGE_PATH`

2019-11-17 20:22 UTC, TSC21 requested changes
Is there any particular reason why this shouldn't be an SDF element instead of an env variable?

2019-11-17 21:16 UTC, Jaeyoung-Lim commented
@TSC21 I added the option to configure the path as an environment variable so that changing the path can be done without editing the sdf file. Would it also make sense to add it as a sdf element?

2019-11-17 21:45 UTC, TSC21 commented
> Would it make sense to also add it as a sdf element?

I think it only makes sense to add it as an SDF element. You can default the value on code and if one wants to change the path, it just changes it by vehicle where this element is set. I don't see a strong reason why it would be better to set it as an environment variable, considering that plugins are easily configurable by SDF.

2019-11-20 08:25 UTC, Jaeyoung-Lim commented
Had discussion offline with @TSC21 and came to the conclusion that this is not good practice

2019-11-20 08:25 UTC, closed without merging