Added baylands model and example world
PX4/PX4-SITL_gazebo-classic pull request #405
Opened 2020-02-03 18:24 UTC by ahcorde

Added baylands 
 - model
 - example world

![baylands](https://user-images.githubusercontent.com/1933907/73679471-b7d0d780-46ba-11ea-9a4c-e4d8bd5f1dba.jpg)

co-author: @tfoote

2020-02-03 18:56 UTC, tfoote commented
Please test this out as is for feedback.  Before it's ready to merge we're going to move the models to be hosted at gazebosim.org/models so that the model data isn't stored here in this repository. But before we finalize the model upload there we'd like to get any feedback from reviews here.

2020-02-05 15:00 UTC, Jaeyoung-Lim commented
@tfoote @ahcorde This extremely cool!

These worlds would be really useful for testing different functionalities in the flight controllers such as terrain following, obstacle avoidance.

a. I was not able to spawn the model properly. The gazebo segfaults when trying to run this model. Are there any minimum requirements regarding gazebo versions? 
```
[ 3365.113498] gzclient[17944]: segfault at 120 ip 00007f50cb45efa0 sp 00007f501d15f8a8 error 4 in libpthread-2.27.so[7f50cb455000+1a000]
```

b. Would it be possible to get the GPS coordinates of the origins? That way we can also align the GPS and show the map accordingly on QGroundControl

2020-02-05 15:03 UTC, ahcorde commented
You need to use a gazebo version which support heighmaps. I tested with Gazebo 9 and 11. World are quite big, maybe a decent GPU.

I have all the gps origins, where I should include it?

2020-03-11 07:17 UTC, mrivi commented
I tested this and I was able to load the worlds however it takes forever, around 3 minutes

2020-03-18 16:02 UTC, Jaeyoung-Lim commented
@ahcorde I see that the models have not been added to the model database. Are there any plans to add the models in the database anytime soon?

2020-03-18 16:06 UTC, ahcorde commented
The PR to upload the models is still open https://bitbucket.org/osrf/gazebo_models/pull-requests/360

2020-03-20 10:51 UTC, Jaeyoung-Lim commented
@ahcorde On the gps origins, I am trying to come up with a way where the gps origin of the world is defined in the world file as in https://github.com/PX4/sitl_gazebo/pull/438

Once we get this cleared, it would be great if we can get the gps coordinates of those large models so we can match them with the groundstation map UI

2020-03-24 10:02 UTC, Jaeyoung-Lim commented
@ahcorde How can we coordinate on getting the gps origins of those worlds? 

This will be simply defining `spherical_coordinates` as done in #441

2020-03-24 10:07 UTC, ahcorde commented
```
    os.environ["PX4_HOME_LAT"] = "37.413534";
    os.environ["PX4_HOME_LON"] = "-121.996561";
    os.environ["PX4_HOME_ALT"] = "1.3";
```

2020-03-24 10:09 UTC, TSC21 commented
> ```
>     os.environ["PX4_HOME_LAT"] = "37.413534";
>     os.environ["PX4_HOME_LON"] = "-121.996561";
>     os.environ["PX4_HOME_ALT"] = "1.3";
> ```

These should be added to the world file itself with the spherical_coordinates tag. Although I would assume this needs to be on the Gazebo model server instead.

2020-03-24 10:09 UTC, Jaeyoung-Lim commented
@ahcorde Awesome, thanks. Do you have a ETA for this model to be deployed in the model database?

2020-03-24 10:11 UTC, ahcorde commented
You can see in this other repo how this [code](https://github.com/osrf/uav_testing/blob/ros2/yosemite_valley/launch/drone_yosemite.launch.py) is being used

2020-03-24 10:11 UTC, ahcorde commented
I don't know the meaning of ETA.

2020-03-24 10:14 UTC, TSC21 commented
> You can see in this other repo how this [code](https://github.com/osrf/uav_testing/blob/ros2/yosemite_valley/launch/drone_yosemite.launch.py) is being used

We won't be using launch files. As @Jaeyoung-Lim said, the logic way of doing it is setting the LLA directly in the world file.

> I don't know the meaning of ETA.

What is the time estimate to have them available in the database? (Estimated Time of Arrival)

2020-03-24 10:19 UTC, ahcorde commented
@tfoote ping

2020-03-25 18:22 UTC, Jaeyoung-Lim requested changes
Thanks for getting it merged in the model database.
Could you squash the commits so that large files don't get merged in the repo?

Thanks!

2020-03-25 18:22 UTC, Jaeyoung-Lim commented on worlds/baylands.world
> +
Could you define the gps origin as defined in https://github.com/PX4/sitl_gazebo/blob/master/worlds/sonoma_raceway.world#L12 ?

2020-03-25 22:36 UTC, Jaeyoung-Lim approved these changes
Looks good on my side, thanks!

I don't see the models in http://models.gazebosim.org/ yet. Do you know when the model will be deployed?

Would be better if we merge once the models are available in the model database

2020-03-26 00:29 UTC, Jaeyoung-Lim commented
It is now in the model database and looks pretty good

[![Demo](https://img.youtube.com/vi/ir1fwOLcd4E/0.jpg)](https://youtu.be/ir1fwOLcd4E)

Thanks @ahcorde !

2020-03-26 00:36 UTC, TSC21 approved these changes

2020-03-26 00:36 UTC, merged

2020-03-26 00:37 UTC, TSC21 commented
@hamishwillee good for docs :) we should document what worlds we have available.

2020-03-26 00:58 UTC, hamishwillee commented
@TSC21 @Jaeyoung-Lim Re https://github.com/PX4/sitl_gazebo/pull/405#issuecomment-604161789

That would be nice; who would like to volunteer?
This does not require my specific expertise, though of course I am very happy to review.

I think this might be worth adding this as a sub page of Gazebo. Along with splitting out the vehicle models into their own pages. - e.g. http://dev.px4.io/master/en/simulation/gazebo.html#quadrotor

Thoughts?

2020-03-26 11:03 UTC, Jaeyoung-Lim commented
@hamishwillee I will write it down! I think it makes sense to separate the pages since the page is getting a bit long now

2020-03-27 00:10 UTC, hamishwillee commented
Great. FYI, started the process https://github.com/PX4/Devguide/pull/995