Handle videostream info and mode switches for geotagged images plugin
PX4/PX4-SITL_gazebo-classic pull request #426
Opened 2020-03-09 21:55 UTC by Jaeyoung-Lim

This PR improves handling the mavlink camera protocol in the `geotagged_images_plugin`, by handling the following mavlink messages
- `MAV_CMD_REQUEST_VIDEO_STREAM_STATUS`
- `MAV_CMD_REQUEST_VIDEO_STREAM_INFORMATION`
- [`MAV_CMD_SET_CAMERA_MODE`](https://mavlink.io/en/services/camera.html#camera-modes)
 

To test:
```
make px4_sitl gazebo_typhoon_h480
```

2020-03-09 22:09 UTC, hamishwillee commented
FWIW this is cool, as it will allow test of camera mode switching in UIs via simulation :-). This will require update to this section: https://dev.px4.io/master/en/simulation/gazebo.html#simulated-survey-camera

2020-03-10 10:41 UTC, julianoes approved these changes
Nice!

2020-03-10 12:05 UTC, merged

2020-03-10 12:05 UTC, TSC21 requested changes
Some minor things but the rest seems good. Nice work!

2020-03-10 12:05 UTC, TSC21 commented on src/gazebo_geotagged_images_plugin.cpp
> +        2048,                                                   // Bit rate (made up)
@Jaeyoung-Lim can we make the frame rate, bit rate, rotation and FOV configurable by SDF elements of the plugin? Makes more sent to me than hard-coding them.

2020-03-10 12:05 UTC, TSC21 commented on src/gazebo_geotagged_images_plugin.cpp
> +        _mode = CAMERA_MODE_IMAGE;
Is this right? Shouldn't it be:

```suggestion
        _mode = CAMERA_MODE_VIDEO;
```

of course bellow would be
```c++
        _mode = CAMERA_MODE_IMAGE;
```

2020-03-10 12:06 UTC, TSC21 commented
@LorenzMeier you got ahead of me ahah