models: fix iris propellors with Gazebo 11
PX4/PX4-SITL_gazebo-classic pull request #504
Opened 2020-05-26 11:51 UTC by julianoes

Without this change the optical flow models have the propellors in a completely wrong location and don't fly.

2020-05-26 11:52 UTC, TSC21 requested changes
You need to update the model config as well.

https://github.com/PX4/sitl_gazebo/blob/master/models/iris_opt_flow/model.config#L5

2020-05-26 12:17 UTC, julianoes commented
> You need to update the model config as well.

Do I? Because it works :thinking:, and it was wrong before as well. So it seems like the model config one is redundant.

2020-05-26 12:38 UTC, TSC21 commented
> > You need to update the model config as well.
> 
> Do I? Because it works , and it was wrong before as well. So it seems like the model config one is redundant.

Not to work but to be consistent inside a database.

2020-05-26 13:24 UTC, Jaeyoung-Lim commented
I think this will break gazebo7 and gazebo9 according to the gazebo documentation: http://gazebosim.org/tutorials?tut=install_dependencies_from_source

2020-05-26 14:51 UTC, julianoes commented
Well, then I don't know what to do. The problem seems to be that the command `gz sdf` uses sdf 1.7 for Gazebo 11 and if I pass `-v 1.6` it says something like "conversion not possible".

So this would mean we need to patch these files at build time :see_no_evil:.

2020-06-25 21:06 UTC, bperseghetti commented
@julianoes @TSC21 where are we at on moving everything forward to 11? I think if anyone wants to cling to 9 they just need to checkout a "gazebo9" branch or something like that so we can roll the sdf forward to allow for more complete modeling options in 1.7 that have been out and standard now for last ~1.5 years. I assume at some point there will be sitl_ignition?

2020-06-26 07:00 UTC, julianoes commented
@bperseghetti can we install Gazebo 11 on Ubuntu 18.04 which we still support? If so, that would be a way forward.

2020-06-26 09:01 UTC, TSC21 commented
> @bperseghetti can we install Gazebo 11 on Ubuntu 18.04 which we still support? If so, that would be a way forward.

The problem is not the OS, but rather the Gazebo 11 support. There are some things that need to worked on before first to add that support. It might actually include create a legacy model folder, or in the end as suggested, create a legacy branch to Gazebo <=9.

2020-06-27 02:57 UTC, bperseghetti commented
@julianoes haven't used gazebo 11 on 18.04, Although since it was released back in Jan 2019 I would imagine it has to work in 18.04 one way or another. We were all too excited to finally get rid of all python 2.7 issues for good by jumping to 20.04 soon as it hit beta and have been using it for many months now. @TSC21 do we have a doc highlighting any unresolved issues with using gazebo11? As far as quads and rovers go it seems to work great for us but we are not using boats, VTOL, planes etc.

2020-06-27 06:07 UTC, TSC21 commented
> @julianoes haven't used gazebo 11 on 18.04, although since it was released back in Jan 2019 I would imagine it has to work in 18.04 one way or another. We were all too excited to finally get rid of all python 2.7 issues for good by jumping to 20.04 soon as it hit beta and have been using it for many months now. @TSC21 do we have a doc highlighting any unresolved issues with using gazebo11? As far as quads and rovers go it seems to work great for us but we are not using boats, VTOL, planes etc.

No there is no document. Though, as you might understand, as long as we have hard dependenckes on things like the SDF formats, we have to make decisions regarding how we are going to support new versions and still keep back support to later ones (at least Gazebo 9).

2020-08-16 18:45 UTC, Jaeyoung-Lim commented
@julianoes Is this still a valid issue? It seems like the CI can run mavsdk tests without this change

2020-08-24 05:03 UTC, julianoes commented
@Jaeyoung-Lim do we have Gazebo 11 in CI?

2020-08-24 07:03 UTC, Jaeyoung-Lim commented
@julianoes Yes! Firmware mavsdk tests are running on gazebo11

2020-08-24 08:19 UTC, julianoes commented
@Jaeyoung-Lim nice! But we're not running the iris_opt_flow model. I remember that all models based on top of iris did not work properly.

2020-08-24 08:20 UTC, Jaeyoung-Lim commented
@julianoes Ah, okay let me give that a try

2020-08-25 12:50 UTC, julianoes commented
@Jaeyoung-Lim you're right with Gazebo 11 on Ubuntu it works just fine. I'll try to rebuild my Gazebo on Arch Linux.

2020-10-05 09:23 UTC, julianoes commented
FYI: this is still a problem on Arch Linux. I don't know why though as gazebo and sdf versions are identical to Ubuntu 20.04 where it works just fine. For now I have a script to workaround it locally:

```
find . -name "*.config" -type f -exec sed -i "s/sdf version='1.4'/sdf version='1.7'/g" {} \;
find . -name "*.config" -type f -exec sed -i "s/sdf version='1.5'/sdf version='1.7'/g" {} \;
find . -name "*.config" -type f -exec sed -i "s/sdf version='1.6'/sdf version='1.7'/g" {} \;

find . -name "*.sdf" -type f -exec sed -i "s/sdf version='1.4'/sdf version='1.7'/g" {} \;
find . -name "*.sdf" -type f -exec sed -i "s/sdf version='1.5'/sdf version='1.7'/g" {} \;
find . -name "*.sdf" -type f -exec sed -i "s/sdf version='1.6'/sdf version='1.7'/g" {} \;

find . -name "*.sdf.jinja" -type f -exec sed -i "s/sdf version='1.4'/sdf version='1.7'/g" {} \;
find . -name "*.sdf.jinja" -type f -exec sed -i "s/sdf version='1.5'/sdf version='1.7'/g" {} \;
find . -name "*.sdf.jinja" -type f -exec sed -i "s/sdf version='1.6'/sdf version='1.7'/g" {} \;
```

2020-10-05 09:23 UTC, closed without merging