models: add iris_gps_height
PX4/PX4-SITL_gazebo-classic pull request #537
Opened 2020-06-26 11:43 UTC by julianoes

This adds a model based on default iris but using GPS height instead of baro.

The only change is really the one param. @Jaeyoung-Lim do you think this is the right approach?

2020-06-26 11:48 UTC, Jaeyoung-Lim requested changes

2020-06-26 11:48 UTC, Jaeyoung-Lim commented on models/iris_gps_height/model.config
> +  <sdf version='1.4'>iris.sdf</sdf>
The sdf name should match the model name e.g. `iris_gps_height.sdf`

2020-06-26 11:48 UTC, Jaeyoung-Lim commented on models/iris_gps_height/iris_gps_height.sdf
> +<sdf version='1.7'>
Is there anything different compared to the default iris? If there is nothing different, you can also just reference to default iris as done in https://github.com/PX4/sitl_gazebo/tree/master/models/iris_opt_flow

2020-06-26 11:49 UTC, Jaeyoung-Lim commented on models/iris_gps_height/iris_gps_height.sdf
> +<sdf version='1.7'>
I guess same problem as before, but since we don't officially support sdf version 1.7 I think it is better we keep it as 1.6

2020-06-26 11:53 UTC, TSC21 commented
So the only difference here is the removal of the baro plugin? Can't this be a condition added to xacro and defined at build time on CMake?

2020-06-26 12:11 UTC, julianoes commented
@TSC21 no we don't even need to disable baro. I just need to set `EKF2_HGT_MODE` to 1 in the startup.

2020-06-26 12:21 UTC, TSC21 commented
> @TSC21 no we don't even need to disable baro. I just need to set `EKF2_HGT_MODE` to 1 in the startup.

Ah so that's even simpler. @Jaeyoung-Lim do we already have a way of loading the same model and mixer, but with a different iniit.d config file using the sitl_run.sh script? That would be the way to go here. No need for a new model in those cases.

2020-06-26 12:29 UTC, Jaeyoung-Lim commented
@TSC21 Right, I think I can add that logic - but not sure how we should handle it with the make command

@julianoes To unblock you, you can just do something like
```
  <model name='iris_gps_height'>
    <include>
      <uri>model://iris</uri>
    </include>
</model>
```

2020-07-02 12:09 UTC, julianoes commented
Ok, it turns out even thought the param `EKF2_HGT_MODE` supposedly requires a reboot it is applied immediately. This means I can just set the param at the beginning of a test before takeoff and I don't need to have yet another SITL model for it.

2020-07-02 12:09 UTC, closed without merging