Fix for ground truth attitude.
PX4/PX4-SITL_gazebo-classic pull request #62
Opened 2016-12-02 04:06 UTC by jgoppert

This is a hardcore rewrite of the the simulated attitude to be very explicit about which fame vectors are in and follow common conventions used in the firmware. I have verified all of the ground truths match via plots with px4tools and have flown this in SITL.

![image](https://cloud.githubusercontent.com/assets/473772/20822664/a84ebc00-b81a-11e6-80ad-7a16beb2204a.png)

2016-12-02 04:08 UTC, jgoppert commented
@bkueng Please review.

2016-12-02 08:36 UTC, LorenzMeier requested changes
The rewrite is great cleanup, but we need to make sure that we are not changing anything that people rely on (e.g. airspeed) substantially as part of it without re-validating it (which we haven't done).

2016-12-02 08:36 UTC, LorenzMeier commented on src/gazebo_mavlink_interface.cpp
> +  sensor_msg.diff_pressure = 0.5f*q*vel_b.x*vel_b.x / 100;
The old formulation used X and Z - this will break tailsitter VTOLs. The right thing would be to project the body x/z vel based on angle of attack.

2016-12-02 09:03 UTC, jgoppert commented
To help speed up getting this in I just reverted the math change so we can revisit it later.

2016-12-03 15:14 UTC, jgoppert commented
@LorenzMeier @bkueng  good to merge? The ground truth is incorrect without this.

2016-12-03 15:47 UTC, jgoppert commented
Ground truth without this patch: 

![image](https://cloud.githubusercontent.com/assets/473772/20860418/cc3ae856-b945-11e6-8c5c-ab4edd28c2a9.png)

2016-12-03 15:56 UTC, LorenzMeier commented
Thanks!

2016-12-03 15:56 UTC, merged