gazebo_gps_plugin fix and enhancement
PX4/PX4-SITL_gazebo-classic pull request #635
Opened 2020-10-14 14:42 UTC by spurnvoj

- fixed loading of 'topic' parameter from SDF
- renamed class member variables to the consistent coding convention (Google C++ style guide)
- fixed crashing of the plugin due to reading from shared variables

2020-10-14 15:03 UTC, Jaeyoung-Lim requested changes
Thanks for the contribution and the fix!

It would be better if we can remove the white spaces fixes

2020-10-14 15:03 UTC, Jaeyoung-Lim commented on include/gazebo_gps_plugin.h
> +#endif  // _GAZEBO_GPS_PLUGIN_HH_
I know that we don't have style checks in this repository, but can you remove arbitrary white space fixes? At some point we need to introduce style fixes in this repo, but this shouldn't be done in a file to file basis.

2020-10-14 15:09 UTC, spurnvoj commented on include/gazebo_gps_plugin.h
> +#endif  // _GAZEBO_GPS_PLUGIN_HH_
I probably called auto-indent and style fix in the header file. I will revert it. The cpp file should be fine.

2020-10-19 11:33 UTC, Jaeyoung-Lim approved these changes
Thanks!

2020-10-19 11:33 UTC, merged