Adding Model of BlueROV2 (heavy configuration)
PX4/PX4-SITL_gazebo-classic pull request #637
Opened 2020-10-20 17:47 UTC by lennartalff

This pull request refers to the pull request [#16004](https://github.com/PX4/Firmware/pull/16004) in the PX4 Firmware repository.

This PR adds the gazebo model of the BlueROV2 in heavy configuration.

2020-10-20 17:49 UTC, TSC21 commented
@lennartalff cool! You mind attaching a screenshot of it? Thanks

2020-10-20 18:11 UTC, lennartalff commented
@TSC21 Here you are!
<img width="816" alt="bluerov2-1" src="https://user-images.githubusercontent.com/33184858/96626696-1d7bf700-1310-11eb-91b8-fab4976ec9d0.png">
<img width="816" alt="bluerov2-2" src="https://user-images.githubusercontent.com/33184858/96626702-1e148d80-1310-11eb-8309-ca5911638e4e.png">
<img width="816" alt="bluerov2-3" src="https://user-images.githubusercontent.com/33184858/96626703-1ead2400-1310-11eb-9af8-686179bc5350.png">

2020-10-20 18:22 UTC, TSC21 commented
> @TSC21 Here you are!
> <img alt="bluerov2-1" width="816" src="https://user-images.githubusercontent.com/33184858/96626696-1d7bf700-1310-11eb-91b8-fab4976ec9d0.png">
> <img alt="bluerov2-2" width="816" src="https://user-images.githubusercontent.com/33184858/96626702-1e148d80-1310-11eb-8309-ca5911638e4e.png">
> <img alt="bluerov2-3" width="816" src="https://user-images.githubusercontent.com/33184858/96626703-1ead2400-1310-11eb-9af8-686179bc5350.png">

Looks awesome!

2020-10-20 21:33 UTC, Jaeyoung-Lim requested changes
Thanks! This is really awesome!

I have just one minor question
- Does the `heavy` suffix imply that there are other configurations that are planned to be added? If not, would it make sense to simplify the namespace by removing the `heavy` suffix?

2020-10-20 21:33 UTC, Jaeyoung-Lim commented on models/uuv_bluerov2_heavy/uuv_bluerov2_heavy.sdf
> +            <gpsSubTopic>/gps</gpsSubTopic>
```suggestion
```

2020-10-20 21:33 UTC, Jaeyoung-Lim commented on models/uuv_bluerov2_heavy/uuv_bluerov2_heavy.sdf
> +            <baroTopic>/baro</baroTopic>
Just curious, for UUVs, the barometer model here will not match the barometer on the real vehicle right? How does this usually influence the state estimation on the vehicle? Do we need to make it constant?

2020-10-20 21:45 UTC, lennartalff commented on models/uuv_bluerov2_heavy/uuv_bluerov2_heavy.sdf
> +            <baroTopic>/baro</baroTopic>
In fact we currently use external vision estimation for the height. So the ekf2 ignores the input of the baro. But in the future i would like to modify the pressure->height calculation in `VehicleAirdata.cpp` https://github.com/PX4/Firmware/blob/0b74076265edda2ac34cb9c4addcfeea7277d3a2/src/modules/sensors/vehicle_air_data/VehicleAirData.cpp#L245 to check if the vehicle type is a submarine and adapt the equation accordingly.

Then i would also modify the barometric pressure simulation accordingly to get reasonable results.

2020-10-20 21:54 UTC, lennartalff commented
@Jaeyoung-Lim in fact the "heavy" suffix means that this configuration uses 8 thrusters. The standard configuration only has 6. So in case I or someone else will add the standard configuration for this vehicle no confusing renaming of the models is needed. So i think it would be a good idea to keep the suffix.

2020-10-21 07:05 UTC, Jaeyoung-Lim approved these changes
Thanks!

Is there anymore outstanding issues? Could you make it as ready to review?

2020-10-21 14:13 UTC, merged

2020-10-22 00:41 UTC, hamishwillee commented
Docs? 
Normally in table here https://dev.px4.io/master/en/simulation/gazebo.html#running-the-simulation and with image here: https://dev.px4.io/master/en/simulation/gazebo_vehicles.html 

If there is an associated "world" then here: https://dev.px4.io/master/en/simulation/gazebo_worlds.html