gazebo_mavlink_interface plugin: handle all the data
PX4/PX4-SITL_gazebo-classic pull request #669
Opened 2020-12-12 18:40 UTC by BazookaJoe1900

let gazebo_mavlink_interface to handle data between the PX4 and Gazebo, and mavlink_interface should only handle interface.
this reduce the need to create interface functions such:
https://github.com/PX4/PX4-SITL_gazebo/compare/master...BazookaJoe1900:pr-mavlink_interface_handle_msg#diff-9062723eb3c075bea8b65c52343ccba0fd202802bd05ffeb2c9f394680b8e7abL582

and that also make much easier to add messages, other then the one that current used (MAVLINK_MSG_ID_HIL_ACTUATOR_CONTROLS)

2020-12-12 20:11 UTC, Jaeyoung-Lim requested changes
The intention of previous PR https://github.com/PX4/PX4-SITL_gazebo/pull/582 was that the `gazebo_mavlink_interface` should not need to understand mavlink and this should be handled in the `mavlink_interface` object. This seems to be reverting this change

Could you elaborate on what problem you are trying to solve?

2020-12-12 20:43 UTC, BazookaJoe1900 commented
but 'gazebo_mavlink_interface' does know mavlink messages, it sends all the data.
on the other hand 'mavlink_interface' almost don't know any mavlink messages, except to MAVLINK_MSG_ID_HIL_ACTUATOR_CONTROLS. it does know 'interfacing': how to open, close, forward and so on.

the problem I solved is that for any new message that should passed to the simulator, it can be handled on 'gazebo_mavlink_interface' only.
In my case I needed such message, and didn't want to "pass" the data from 'mavlink_interface' to 'gazebo_mavlink_interface' by functions

2020-12-12 20:55 UTC, Jaeyoung-Lim commented
@BazookaJoe1900 The mavlink linking will be removed. I have created my WIP as a draft PR for context. (https://github.com/PX4/PX4-SITL_gazebo/pull/671) This is already being used in the px4-jsbsim-bridge and eventually be a standalone repository. 

If I understand correctly, is what you are trying to do to pass other mavlink messages that are not HIL messages through this plugin? If so, IMHO I think this should be using a different port. For example, the geotagged_images_plugin talks to the firmware with mavlink through a separate UDP port.

I would be open for suggestions, but this is the general direction I was moving towards to

2020-12-13 12:47 UTC, BazookaJoe1900 commented
ok, With you changes on #671 I don't see much reason for this PR.

2020-12-13 12:47 UTC, closed without merging