Removed unused computation of CoG
PX4/PX4-SITL_gazebo-classic pull request #737
Opened 2021-04-09 15:40 UTC by manumerous

In the lift drag plugin there were a few lines of code used to compute the center of gravity of the respective link. Since the variables themselfes are unused I propose to remove them.

Let me know if the change in the formatting is a problem for your conventions. I can change it if needed.

2021-04-09 16:17 UTC, Jaeyoung-Lim commented
@manumerous Why was this closed?

2021-04-09 16:58 UTC, manumerous commented
Some checks failed. So i wanted to investigate more before using somebody's time.

2021-04-09 16:58 UTC, manumerous commented
But I could not delete the PR so i just closed it.

2021-04-09 17:12 UTC, Jaeyoung-Lim commented
@manumerous I reopened, since the failures were not related to the PR

2021-04-09 17:22 UTC, Jaeyoung-Lim requested changes
Can you remove the whitespace fixes? I think this should belong to a different PR

2021-04-10 10:33 UTC, manumerous commented
I removed all the changes due to a different formatting.

2021-04-10 10:39 UTC, Jaeyoung-Lim approved these changes
Thanks!

2021-04-10 10:40 UTC, merged