Fix bug in iris_hitl.sdf
PX4/PX4-SITL_gazebo-classic pull request #778
Opened 2021-07-01 22:37 UTC by rocketengineer1982

Fixed a bug that prevents iris_hitl from flying.  See https://github.com/PX4/PX4-SITL_gazebo/issues/768#issue-912062536.

2021-07-02 04:23 UTC, Jaeyoung-Lim requested changes
Thanks for the fix!

I had a few questions along the lines

2021-07-02 04:23 UTC, Jaeyoung-Lim commented on models/iris_hitl/iris_hitl.sdf
> +      <use_tcp>1</use_tcp>
Is this necessary?

2021-07-02 04:23 UTC, Jaeyoung-Lim commented on models/iris_hitl/iris_hitl.sdf
> +      <gpsSubTopic>/gps0</gpsSubTopic>
I don't think you need this tag. Can you try removing this?

2021-07-02 04:23 UTC, Jaeyoung-Lim commented on models/iris_hitl/iris_hitl.sdf
> +      <mavlink_tcp_port>4560</mavlink_tcp_port>
Since you are using HITL, you are not using `mavlink_tcp_port`

2021-07-02 04:23 UTC, Jaeyoung-Lim commented on models/iris_hitl/iris_hitl.sdf
> +      <parent>base_link</parent>
unnecessary change?

2021-07-02 04:23 UTC, Jaeyoung-Lim commented on models/iris_hitl/iris_hitl.sdf
> +<sdf version='1.5'>
Is there a specific reason you had to lower the sdf version?

2021-07-02 04:23 UTC, Jaeyoung-Lim commented on models/iris_hitl/iris_hitl.sdf
> -        <use_parent_model_frame>1</use_parent_model_frame>
Could you explain why this was necessary?

2021-07-13 07:42 UTC, Jaeyoung-Lim commented
@rocketengineer1982 Any updates?

2022-05-20 02:02 UTC, julianoes commented
It's not clear to me what this should fix and how. And there was no follow up, so I'm closing it.

2022-05-20 02:02 UTC, closed without merging