gimbal: fix yaw angle at pitch -90 degrees
PX4/PX4-SITL_gazebo-classic pull request #885
Opened 2022-07-25 04:02 UTC by julianoes

This fixes the gimbal at pitch -90 degrees. It is based on the 3-1-2 intrinsic TaitBryan angles rather than the 3-2-1 provided by the MAVLink headers.

Same as https://github.com/PX4/PX4-Autopilot/pull/19951

2022-07-29 08:55 UTC, Jaeyoung-Lim requested changes
@julianoes Not sure if this is `yaw` is defined a type somewhere, but 
Could you recheck if the code actually compiles?
```
/__w/PX4-SITL_gazebo/PX4-SITL_gazebo/src/gazebo_gimbal_controller_plugin.cpp:837:11: error: ‘yaw’ does not name a type
  837 |     const yaw pitchRad = euler[0];
      |           ^~~
/__w/PX4-SITL_gazebo/PX4-SITL_gazebo/src/gazebo_gimbal_controller_plugin.cpp:838:11: error: ‘yaw’ does not name a type
  838 |     const yaw rollRad = euler[1];
      |           ^~~
/__w/PX4-SITL_gazebo/PX4-SITL_gazebo/src/gazebo_gimbal_controller_plugin.cpp:839:11: error: ‘yaw’ does not name a type
  839 |     const yaw yawRad = euler[2];
      |           ^~~
/__w/PX4-SITL_gazebo/PX4-SITL_gazebo/src/gazebo_gimbal_controller_plugin.cpp:842:26: error: ‘rollRad’ was not declared in this scope; did you mean ‘rollPid’?
  842 |     this->rollSetpoint = rollRad;
      |                          ^~~~~~~
      |                          rollPid
/__w/PX4-SITL_gazebo/PX4-SITL_gazebo/src/gazebo_gimbal_controller_plugin.cpp:843:27: error: ‘pitchRad’ was not declared in this scope; did you mean ‘pitchPid’?
  843 |     this->pitchSetpoint = pitchRad;
      |                           ^~~~~~~~
      |                           pitchPid
/__w/PX4-SITL_gazebo/PX4-SITL_gazebo/src/gazebo_gimbal_controller_plugin.cpp:844:25: error: ‘yawRad’ was not declared in this scope; did you mean ‘yawPid’?
  844 |     this->yawSetpoint = yawRad;
      |                         ^~~~~~
      |                         yawPid
```

2022-08-01 06:40 UTC, julianoes commented
Whoops, what have I done.

2022-08-01 06:43 UTC, julianoes commented
Should be fixed. I must have messed it up when I cleaned it up to commit.

2022-08-01 07:19 UTC, Jaeyoung-Lim approved these changes
LGTM! Thanks!

2022-08-01 07:19 UTC, merged