Fix: deleted <robotNamespace> in depth_camera.sdf.jinja
PX4/PX4-SITL_gazebo-classic pull request #983
Opened 2023-05-14 12:29 UTC by ChanJoon

In previous commit, @Cavalletta98 added <robotNamespace> tag in this model.

> e5836d3a5b28b670e8e94aa5fea7b767bb33a745

but this had a serious impact on PX4-Avoidance and other use case of depth camera in custom UAV model.
The difference in the presence of this tag is as follows:

`$ roslaunch local_planner local_planner-depth_camera.launch`

if <robotNamespace> exists:
`$rostopic list` 
```bash
# copied only related topics
/iris_obs_avoid/camera/depth/camera_info
/iris_obs_avoid/camera/depth/image_raw
/iris_obs_avoid/camera/depth/points
/iris_obs_avoid/camera/parameter_descriptions
/iris_obs_avoid/camera/parameter_updates
/iris_obs_avoid/camera/rgb/camera_info
/iris_obs_avoid/camera/rgb/image_raw
/iris_obs_avoid/camera/rgb/image_raw/compressed
/iris_obs_avoid/camera/rgb/image_raw/compressed/parameter_descriptions
/iris_obs_avoid/camera/rgb/image_raw/compressed/parameter_updates
/iris_obs_avoid/camera/rgb/image_raw/compressedDepth
/iris_obs_avoid/camera/rgb/image_raw/compressedDepth/parameter_descriptions
/iris_obs_avoid/camera/rgb/image_raw/compressedDepth/parameter_updates
/iris_obs_avoid/camera/rgb/image_raw/theora
/iris_obs_avoid/camera/rgb/image_raw/theora/parameter_descriptions
/iris_obs_avoid/camera/rgb/image_raw/theora/parameter_updates
```
else (this commit version or before  e5836d3a5b28b670e8e94aa5fea7b767bb33a745)
```bash
# copied only related topics
/camera/depth/camera_info
/camera/depth/image_raw
/camera/depth/points
/camera/parameter_descriptions
/camera/parameter_updates
/camera/rgb/camera_info
/camera/rgb/image_raw
/camera/rgb/image_raw/compressed
/camera/rgb/image_raw/compressed/parameter_descriptions
/camera/rgb/image_raw/compressed/parameter_updates
/camera/rgb/image_raw/compressedDepth
/camera/rgb/image_raw/compressedDepth/parameter_descriptions
/camera/rgb/image_raw/compressedDepth/parameter_updates
/camera/rgb/image_raw/theora
/camera/rgb/image_raw/theora/parameter_descriptions
/camera/rgb/image_raw/theora/parameter_updates
```
Since PX4-Avoidance utilizes the "/camera/depth/points" topic in their launch file, it might be more logical or appropriate to exclude this tag.
[`<arg name="pointcloud_topics" default="[/camera/depth/points]"/>`](https://github.com/PX4/PX4-Avoidance/blob/master/local_planner/launch/local_planner_depth-camera.launch#L5)

I know that using a specific robot namespace is easier for users to customize and utilize for models, but this ultimately depends on the user's needs.

2023-05-14 12:42 UTC, Cavalletta98 commented
The problem was about simulating multiple drones for PX4 avoidance software. In this way you can have separate topics with namespace. If you remove It,It Will be impossible to simulate multiple drones

2023-05-14 12:54 UTC, ChanJoon commented
> The problem was about simulating multiple drones for PX4 avoidance software. In this way you can have separate topics with namespace. If you remove It,It Will be impossible to simulate multiple drones

Thank you for your quick feedback!
As you said, when we use multiple drones, we should use <robotNamespace> in our camera model.

But I think it is depend on the user who wants to simulate multiple drones or different camera topics.
Given the reliance of PX4-Autopilot and PX4-Avoidance on this repository, it may seem more intuitive to remove the <robotNamespace> tag. (I personally encountered some challenges while trying to use `local_planner_depth-camera.launch` for both PX4-Avoidance and my own navigation system.)

2023-05-14 13:02 UTC, Cavalletta98 commented
I really don't know

2023-05-14 13:05 UTC, Jaeyoung-Lim requested changes
Why not update the avoidance package to include the namespace?

2023-05-14 13:07 UTC, Cavalletta98 commented
Probably was not possible. I didn't remember

2023-05-14 13:13 UTC, ChanJoon commented
It looks great to update the avoidance package.

I think we have two options. Delete this tag or Update avoidance launch file (i.e <arg name="pointcloud_topics" default="[/iris_obs_avoid/camera/depth/points]"/>)

2023-05-14 13:25 UTC, Cavalletta98 commented
The problem Is that even if we update the avoidance with this fix,something more should be done. Because when i did this fix,It solved only the fact that you can see the camera of the different drones in rviz. 
It should be discussed with the guys of avoidance software in order to do all the things for simulating multiple drones, and so decide where Is the right place to put this tag. Can you please open and issue on avoidance?

2023-05-14 13:51 UTC, ChanJoon commented
As far as I know, @Jaeyoung-Lim is one of the maintainers of the avoidance package.

@Jaeyoung-Lim Could you tell me your opinions?

2023-05-22 14:38 UTC, Jaeyoung-Lim commented
@ChanJoon I would say it is the downstream package(avoidance) that would need to be updated

2023-05-22 15:08 UTC, ChanJoon commented
> @ChanJoon I would say it is the downstream package(avoidance) that would need to be updated

Thanks. I'll close this request and open a new one in the avoidance soon.

2023-05-22 15:08 UTC, closed without merging